[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["kubamik <kubamik9@gmail.com>"]
description = ""
name = "rashdarkmagentacomputer"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.7"
[tool.poetry.dev-dependencies]
