[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["kubamik <kubamik9@gmail.com>"]
description = ""
name = "rashdarkmagentacomputer"
version = "1.0"
[tool.poetry.dependencies]
attr = "^0.3.1"
"discord.py" = "^1.3"
flask = "^1.1"
python = "^3.8"
[tool.poetry.dev-dependencies]
